general.import = [
    "~/.config/alacritty/themes/themes/coolnight-custom.toml"
]

[env]
TERM = "xterm-256color"

[window]
padding.x = 12
padding.y = 12

decorations = "Buttonless"

opacity = 0.7
blur = true

option_as_alt = "Both"

[font]
normal.family = "MesloLGS Nerd Font Mono"

size = 12

[cursor]

style.shape = "Block"
style.blinking = "Always"
blink_interval = 500


