#!/bin/bash

source "$CONFIG_DIR/colors.sh" # Loads all defined colors
# This is a demo config to showcase some of the most important commands.
# It is meant to be changed and configured, as it is intentionally kept sparse.
# For a (much) more advanced configuration example see my dotfiles:
# https://github.com/FelixKratz/dotfiles

PLUGIN_DIR="$CONFIG_DIR/plugins"
ITEM_DIR="$CONFIG_DIR/items"

##### Bar Appearance #####
# Configuring the general appearance of the bar.
# These are only some of the options available. For all options see:
# https://felixkratz.github.io/SketchyBar/config/bar
# If you are looking for other colors, see the color picker:
# https://felixkratz.github.io/SketchyBar/config/tricks#color-picker

sketchybar --bar position=top \
                 height=38 \
                 blur_radius=30 \
                 color=0x00000000  \
                 y_offset=3 \
                 margin=10 \
                 background.drawing=off\
                 image.drawing=off \
                 corner_radius=10 \
                 # border_color=$BG_BORDER_COLOR \
                 # border_width=1 \
                 # corner_radius=10


##### Changing Defaults #####
# We now change some default values, which are applied to all further items.
# For a full list of all available item properties see:
# https://felixkratz.github.io/SketchyBar/config/items
#
# sketchybar --default icon.font="SF Pro:Semibold:15.0" \
#                      icon.color=$WHITE \
#                      label.font="SF Pro:Semibold:15.0" \
#                      label.color=$WHITE                \
#                      background.color=$ITEM_BG_COLOR \
#                      background.corner_radius=5 \
#                      background.height=24 \
#                      padding_left=5                    \
#                      padding_right=5                   \
#                      label.padding_left=4              \
#                      label.padding_right=10             \
#                      icon.padding_left=10               \
#                      icon.padding_right=4
#
default=(
  updates=when_shown
  padding_left=3
  padding_right=3
  icon.font="SF Pro:Semibold:15.0"
  label.font="Jetbrains Mono:Regular:15.0"
  icon.color=$RED2
  label.color=$WHITE
  icon.padding_left=4
  icon.padding_right=4
  label.padding_left=8
  label.padding_right=8
  background.corner_radius=10
  background.color=$ITEM_BG_COLOR
  background.height=30 
  # background.image=/users/alexanderfortunato/.config/sketchybar/images/Background1.png
  # background.drawing=on \
  image_scale=0.5
)


sketchybar --default "${default[@]}"

# It was working when this stuff below was uncommented
# # Add the aerospace_workspace_change event we specified in aerospace.toml
# sketchybar --add event aerospace_workspace_change
#
# for sid in $(aerospace list-workspaces --all); do
#     sketchybar --add item space.$sid center \
#         --subscribe space.$sid aerospace_workspace_change \
#         --set space.$sid \
#         padding_left=10 \
#         background.color=0x44ffffff \
#         background.border_color=$BG_BORDER_COLOR \
#         background.border_width=1 \
#         background.corner_radius=1 \
#         background.height=32 \
#         background.drawing=off \
#         # label="$sid" \
#         click_script="aerospace workspace $sid" \
#         script="$CONFIG_DIR/plugins/aerospace.sh $sid"
# done


# sketchybar --add event aerospace_workspace_change
#
# for sid in $(aerospace list-workspaces --all); do
#     sketchybar --add item space.$sid left \
#         --set space.$sid \
#         background.color=0xffff00d1 \
#         background.corner_radius=5 \
#         background.height=24 \
#         background.border_width=0 \
#         padding_left=8 \
#         padding_right=8 \
#         background.drawing=off \
#         label="$sid" \
#         label.color=0xffffffff \
#         click_script="aerospace workspace $sid && ~/.config/sketchybar/plugins/workspace_update.sh"
# done



# # IMPORTANT: Uncomment this to initialize workspace indicators on startup
# sketchybar --trigger aerospace_workspace_change \
#   FOCUSED_WORKSPACE=$(aerospace list-workspaces --focused)

# # Add workspaces for all monitors
# for monitor in $(aerospace list-monitors --format "%{monitor-appkit-nsscreen-screens-id}"); do
#   for sid in $(aerospace list-workspaces --monitor "$monitor"); do
#     # Determine which display this workspace should be shown on
#     display_id="1"
#     if [ "$sid" -ge 6 ] && [ "$sid" -le 7 ]; then
#       display_id="2"
#     fi
#
#     sketchybar --add item space.$sid left \
#       --set space.$sid display="$display_id" \
#       --subscribe space.$sid aerospace_workspace_change \
#       --set space.$sid \
#       drawing=on \
#       background.color=0x44ffffff \
#       background.corner_radius=5 \
#       background.drawing=on \
#       background.border_color=0xAAFFFFFF \
#       background.border_width=0 \
#       background.height=25 \
#       icon="$sid" \
#       icon.padding_left=10 \
#       icon.shadow.distance=4 \
#       icon.shadow.color=0xA0000000 \
#       label.font="sketchybar-app-font:Regular:16.0" \
#       label.padding_right=20 \
#       label.padding_left=0 \
#       label.y_offset=-1 \
#       label.shadow.drawing=off \
#       label.shadow.color=0xA0000000 \
#       label.shadow.distance=4 \
#       click_script="aerospace workspace $sid" \
#       script="$CONFIG_DIR/plugins/aerospace.sh $sid"
#   done
# done

# # Load Icons on startup for all monitors
# for monitor in $(aerospace list-monitors); do
#   for sid in $(aerospace list-workspaces --monitor "$monitor" --empty no); do
#     apps=$(aerospace list-windows --workspace "$sid" | awk -F'|' '{gsub(/^ *| *$/, "", $2); print $2}')
#
#     sketchybar --set space.$sid drawing=on
#
#     icon_strip=" "
#     if [ "${apps}" != "" ]; then
#       while read -r app; do
#         icon_strip+=" $($CONFIG_DIR/plugins/icon_map_fn.sh "$app")"
#       done <<<"${apps}"
#     else
#       icon_strip=""
#     fi
#     sketchybar --set space.$sid label="$icon_strip"
#   done
# done



# -- Left Side Items --

source $ITEM_DIR/spaces.sh
source $ITEM_DIR/front_app.sh



# -- Center Items --
# source "$CONFIG_DIR/init.lua"

# -- Right Side Items --

source $ITEM_DIR/calendar.sh

# source $ITEM_DIR/NordVPN.sh

source $ITEM_DIR/volume.sh
source $ITEM_DIR/WiFi.sh

source $ITEM_DIR/battery.sh
source $ITEM_DIR/cpu.sh
source $ITEM_DIR/metaserver.sh

# sketchybar --add bracket bracket1 "Control Center,WiFi" "NordVPN,Item-0"\
#            --set         bracket1 background.color=$ITEM_BG_COLOR \
#                                   background.border_width=2 \
#                                   backgound.border_color=$BG_BORDER_COLOR 

sketchybar --add bracket spacesbracket "front_app" "space.1" "space.2" "space.3" "space.4" "space.5" "space.6" \
           --set         spacesbracket background.color=0xde414141 \
                                       background.border_width=2 \
                                       background.border_color=$BG_BORDER_COLOR \
                                       background.height=36 \
                                       background.corner_radius=11 
                                       # background.image=/users/alexanderfortunato/.config/sketchybar/images/Background1.png \
                                       # background.image.scale=1.0

sketchybar --add bracket calendarbracket "calendar" "cpu" "battery" \
           --set         calendarbracket background.color=0xff414141\
                                       background.border_width=2 \
                                       background.border_color=$BG_BORDER_COLOR \
                                       background.height=36 \
                                       background.corner_radius=11 \


sketchybar --add bracket rightbracket1 "volume" "wifi" "MetaServer,Item-0" \
           --set         rightbracket1 background.color=0xde414141\
                                       background.border_width=2 \
                                       background.border_color=$BG_BORDER_COLOR \
                                       background.height=36 \
                                       background.corner_radius=11 \






# sketchybar --add bracket widgets cpu battery volume     \
#            --set         widgets background.color=0xd6000000 \
#                                 background.corner_radius=4  \
#                                 background.height=36 \
#                                 background.border_width=1 \
#                                 background.border_color=$BG_BORDER_COLOR

##### Force all scripts to run the first time (never do this in a script) #####
sketchybar --update
~/.config/sketchybar/init.lua

sketchybar --trigger aerospace_workspace_change \
  FOCUSED_WORKSPACE=$(aerospace list-workspaces --focused)

#


# ~/.config/sketchybar/plugins/workspace_update.sh

